# Generated by Codex on 2026-05-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_rating_session_rename_review_rating_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='learn_skills',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='teach_skills',
            field=models.TextField(blank=True, default=''),
        ),
    ]
